GET http://localhost:3001/user

###

GET http://localhost:3001/user/test2

###

GET http://localhost:3001/user/610f04cd7343800a395c79c6

###

POST http://localhost:3001/user
Content-Type: application/json

{
    "idNum":1565780,
    "name":"quietcalm",
    "avatar": "https://i.ebayimg.com/images/g/QBIAAOSw3BBeemIN/s-l500.jpg",
    "email": "t@t.com"
}

###

PATCH http://localhost:3001/user/610f0899fbc8aa0d170023eb
Content-Type: application/json

{
    "name": "Robbo Lark"
}

###

DELETE http://localhost:3001/user/610f04cd7343800a395c79c6